query Session {
    me {
        ...customerFields
    }
}

mutation Registration($email: String!, $firstName: String!, $lastName: String!, $password: String!) {
    register(email: $email, firstName: $firstName, lastName: $lastName, password: $password) {
        token
        me {
            ...customerFields
        }
    }
}

mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        token
        me {
            ...customerFields
        }
    }
}

mutation RefreshToken {
    refreshToken {
        token
        me {
            ...customerFields
        }
    }
}

fragment customerFields on Customer {
    id
    email
    firstName
    lastName
    fullName
}
